api/graphql/resolvers/benchList.js, api/graphql/resolvers/index.js, api/graphql/resolvers/petitionList.js, api/graphql/schema/index.graphql, api/models/bench.js, api/models/petition.js
- Possibilité d'ajouter une pétition
- Possibilité de supprimer une pétition avec son ID
- Possibilité de demander toutes les pétitions
=> Amélioration de l'API

client/package.json, client/src/App.tsx, client/src/assets/styles/index.scss, client/src/components/Nav/Nav.tsx, client/src/components/Nav/nav.scss, client/src/index.tsx, client/src/pages/Home/Home.tsx, client/src/pages/Map/Map.tsx, client/yarn.lock
- add react-router-dom fro router
- add react-transition-group for route transition
- add gsap for animations
=> :sparkles: add Router and routes transition

client/package.json, client/src/@types/index.d.ts, client/src/components/map/MapManager.ts, client/src/components/map/ProtoMap.tsx, client/src/store/Store.ts, client/yarn.lock
=> Closes: #6 - Amélioration de la map

client/src/components/BurgerButton/BurgerButton.tsx, client/src/components/BurgerButton/burger-button.scss, client/src/pages/Components/Components.tsx, client/src/store/PageStore.ts
Close #46 
- creation du component `BurgerButton`
- animation provisoir open / close
- lié au Store `PageStore`
=> :sparkles: #46 add BurgerButton component

client/src/App.tsx, client/src/components/BurgerButton/BurgerButton.tsx, client/src/components/debug/DebugButton.tsx, client/src/components/debug/DebugPanel.tsx, client/src/components/map/ProtoMap.tsx, client/src/pages/Admin/Transition.tsx, client/src/pages/Bench/Bench.tsx, client/src/pages/Components/Transition.tsx, client/src/pages/Home/Transition.tsx, client/src/pages/Map/Transition.tsx, client/src/pages/Twitter/Transition.tsx, client/src/store/BenchStore.ts, client/src/store/NavigationStore.ts, client/src/store/index.ts
Close #50 
- create `index.ts` in store folder to export all stores
- update import store in all files
- rename `PageStore` to `NavigationStore`
- rename `Store` to `BenchStore`
=> :recycle: #50 refactor stores exports and naming

client/src/components/map/ProtoMap.tsx
=> Détection de la proximité avec une installation et mise à jour du trajet

client/public/index.html, client/src/App.tsx, client/src/assets/styles/app.scss, client/src/assets/styles/index.scss, client/src/assets/styles/variables.scss, client/src/components/Button/Button.tsx, client/src/components/Header/header.scss, client/src/components/Nav/Nav.tsx, client/src/components/Nav/nav.scss, client/src/pages/Home/Home.tsx, client/src/pages/Home/home.scss, client/src/store/NavigationStore.ts, client/src/utils/index.ts
Close #62
- mise en place du `Header`
- mise mettre en place la navigation provisoire
- intégrer la page `Home` sans les animations ni le splash screen
- ajout de la meta `theme-color`
- maintenant la police par défaut appliquée est : _InfiniRegular_
=> page home + header + nav

client/src/components/map/MapController.ts, client/src/components/map/ProtoMap.tsx, client/src/components/map/mapgl.scss
=> Style map et blur 

client/src/config/config.ts, client/src/pages/Admin/Admin.tsx, client/src/pages/Admin/Transition.tsx, client/src/pages/Components/Components.tsx, client/src/pages/Components/Transition.tsx, client/src/pages/Home/Home.tsx, client/src/pages/Home/Transition.tsx, client/src/pages/Installation/Installation.tsx, client/src/pages/Installation/Transition.tsx, client/src/pages/Map/Map.tsx, client/src/pages/Map/Transition.tsx, client/src/pages/Twitter/Transition.tsx, client/src/pages/Twitter/Twitter.tsx, client/src/pages/types.ts
close #72
- les composants **pages** ne sont plus wrappés avec les composants **transitions** 
- les composants **pages** sont maintenant instanciés dans les composants **transitions** 
- ce sont maintenant les composants **transitions** qui sont instanciés dans `App.tsx`
> **ATTENTION** : de légers conflits sont probables au niveau de la page `Installation.tsx` que tu es en train de modifier
=> refacto page and transition component

client/src/components/Countdown/Countdown.tsx
Close #96 
- fixer les conditions de rendu du composant pour qu'il se rende même quand les heures ou les minutes sont égales à 0
=> fix Countdown render condition

client/src/components/SplashscreenAnimation/SplashscreenAnimation.tsx, client/src/components/SplashscreenAnimation/splashscreen-animation.scss, client/src/pages/Home/Home.tsx, client/src/pages/Home/home.scss, client/src/store/NavigationStore.ts, client/src/utils/hooks.ts
Close #122 
- remplacement des filtres SVG par des animations CSS `filter: blur()`
- optimisation du Hook `useWindowSize`
> **N'ayant pas d'iPhone sous la main mais je veux bien que tu testes le rendu et me dises si ça fonctionne bien**
=> fix blur animations on IOS

client/src/components/InstallationThumbnail/InstallationThumbnail.tsx, client/src/components/InstallationThumbnail/installation-thumbnail.scss, client/src/config/config.ts, client/src/pages/Menu/Menu.tsx, client/src/pages/Menu/menu.scss, client/src/pages/Programmation/Programmation.tsx, client/src/pages/Programmation/Transition.tsx, client/src/pages/Programmation/programmation.scss
Close #134 
- création de la page `Programmation`
- création du composant `InstallationThumbnail`
- dynamisation et animations sur la page `Programmation`
=> create Programmation page + Installationthumbnail

client/src/components/InformationsPanel/InformationsPanel.tsx, client/src/components/map/DirectionsController.ts, client/src/components/map/GeoLocationController.ts, client/src/components/map/MapController.ts, client/src/components/map/ProtoMap.tsx, client/src/pages/Installation/Installation.tsx, client/src/pages/Installation/locked/InstallationLocked.tsx, client/src/pages/Installation/locked/installation-locked.scss, client/src/pages/Installation/unlocked/InstallationUnlocked.tsx, client/src/pages/Installation/unlocked/ScrollMagicController.ts, client/src/pages/Installation/unlocked/installation-unlocked.scss
Close #147 
En attente du merge des autres PR pour voir si il n'y a pas de conflits avec l'enregistrement en localStorage, fait sur une autre branche
=> Amélioration du système de déblocage des installations

client/src/components/map/ProtoMap.tsx, client/src/pages/Installation/Installation.tsx, client/src/store/InstallationStore.ts
=> Sauvegarde de la progression de l'utilisateur

client/src/components/SpriteAnimation/SpriteAnimation.tsx, client/src/pages/Installation/unlocked/InstallationUnlocked.tsx, client/src/pages/Installation/unlocked/ScrollMagicController.ts, client/src/pages/Installation/unlocked/installation-unlocked.scss
=> Refacto page Installation

client/src/components/Header/header.scss, client/src/pages/Success/Success.tsx, client/src/pages/Success/Transition.tsx, client/src/pages/Success/success.scss
=> Mise à jour de la page 'Success'

client/src/App.tsx, client/src/components/BurgerButton/BurgerButton.tsx, client/src/components/Header/Header.tsx, client/src/components/MapButton/MapButton.tsx, client/src/components/MapButton/mapButton.scss, client/src/pages/About/About.tsx, client/src/pages/Components/Components.tsx, client/src/pages/Installation/locked/InstallationLocked.tsx, client/src/pages/Installation/unlocked/InstallationUnlocked.tsx, client/src/pages/Map/Map.tsx, client/src/pages/Menu/Transition.tsx, client/src/pages/Menu/menu.scss, client/src/store/NavigationStore.ts
Close #166 
Close #167 
- modification de l'animation du menu en fonction des retours des designers
- amélioration du comportement et de l'animation du composant `MapButton`
- ajout du véritable comportement du `BurgerButton` qui ouvre et ferme le menu
- accès à la navigation de dev en cliquant sur le titre
=> Update menu animation

client/src/@types/index.d.ts, client/src/assets/styles/global.scss, client/src/components/InformationsPanel/InformationsPanel.tsx, client/src/components/InformationsPanel/informationsPanel.scss, client/src/components/map/ProtoMap.tsx, client/src/components/map/mapgl.scss, client/src/pages/Admin/Admin.tsx, client/src/pages/Map/Transition.tsx, client/src/store/InstallationStore.ts, client/src/store/MapStore.ts, client/src/store/NavigationStore.ts, client/src/utils/map.ts
=> Mise à jour de l'InstallationStore

client/src/pages/Finish/Finish.tsx
=> Dynamisation de la page Finish

client/src/@types/index.d.ts, client/src/pages/Admin/Admin.tsx, client/src/pages/Finish/Finish.tsx, client/src/store/InstallationStore.ts
Close #177 
Close #178 
Close #182 
Pour chaque témoignage, on référence : 
- le nom du fichier audio
- les personnes intervenants dans l'extrait
Pour chaque personne on spécifie un ID, le nom et des informations complémentaire si besoin
- le contenu textuel représenté sous forme de tableau
Chaque entité va spécifié le texte retranscrit à l'écrit et l'ID de la personne associé à ce texte
=> Mise à jour du contenu et refacto des témoignages

client/src/components/Header/Header.tsx, client/src/components/Header/header.scss, client/src/pages/Home/Home.tsx, client/src/pages/Home/ScrollMagicController.ts, client/src/pages/Home/Transition.tsx, client/src/pages/Home/home.scss
Close #186
- fix de scrollmagic sur la page home
- amélioration des animations de scroll
- fix afin de pouvoir cacher le header si besoin
- transition de sortie de la page home
=> Home : fix scrollmagic + improve animations

client/src/components/TwitterGallery/TwitterGallery.tsx
Close #129 
- récupération des images twitter en https
=> TwitterGallery : get media url with https

client/src/pages/Installation/Installation.tsx, client/src/pages/Installation/unlocked/installation-unlocked.scss, client/src/pages/Success/Transition.tsx, client/src/pages/Success/success.scss
=> Success page : transition

client/src/pages/Installation/locked/InstallationLocked.tsx
=> Fix bug installationLocked

client/src/components/map/ProtoMap.tsx
=> Added animation on close modal

client/src/components/TwitterGallery/TwitterGallery.tsx, client/src/pages/Installation/unlocked/InstallationUnlocked.tsx, client/src/pages/Installation/unlocked/ScrollMagicController.ts, client/src/store/ScrollMagicStore.ts
- correction du setInterval dans `TwitterGalery`
- controle du live reload des tweets dans `TwitterGallery`
- activer le live reload uniquement quand on est sur la gallery twitter
=> TwitterGallery : control tweet live reload

client/src/pages/Installation/unlocked/ScrollMagicController.ts, client/src/pages/Installation/unlocked/installation-unlocked.scss
Close #192
- fix de l'apparition du text du témoignage dans `InstallationUnlocked`
=> InstallationUnlocked : fix testimony text fade in

client/src/components/MapButton/MapButton.tsx, client/src/components/MapButton/mapButton.scss, client/src/pages/Installation/unlocked/InstallationUnlocked.tsx, client/src/pages/Installation/unlocked/ScrollMagicController.ts
Close #196
- dynamisation du theme de `MapButton` sur la page `InstallationUnlocked`
=> InstallationUnlocked : MapButton dynamic theme
